###### Python ##########

.PHONY : build view clean

build :
		@# "Not much to do here.  I did this in Python"
		chmod +x assn4.py
		chmod +x assn4_unittest.py
view :
		@\less assn4.py

clean :
		@\rm *.pyc
		@\rm -r __pycashe__
